/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " ดูดวงรายวัน",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen overflow-hidden">
          <div className="absolute inset-0 bg-center bg-no-repeat bg-contain opacity-90 max-w-[430px] mx-auto">
            <img
              src="/crystal_ball.jpg"
              alt="Background"
              className="w-full h-full object-cover"
            />
          </div>

          <div className="relative z-10 max-w-[430px] mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
